import React, { useState, useEffect, useCallback } from 'react';
import { X, Car, RotateCcw } from 'lucide-react';
import { AssetNode, Location, CalculationLineItem } from '../lib/types';
import { haversineKm, estimateTravelHours } from '../lib/distanceUtils';
import { uuid } from '../lib/utils';
import SearchableSelect from './SearchableSelect';
import { useModalClose } from '../hooks/useModalClose';

interface FahrtblockDialogProps {
  open: boolean;
  onClose: () => void;
  asset: AssetNode;
  fromLocation: Location | null;   // Basis-Standort der Kalkulation
  toLocation: Location | null;     // Standort des Assets
  allLocations: Location[];
  onConfirm: (items: Partial<CalculationLineItem>[]) => void;
}

export default function FahrtblockDialog({
  open,
  onClose,
  asset,
  fromLocation,
  toLocation,
  allLocations,
  onConfirm,
}: FahrtblockDialogProps) {
  const [fromLocationId, setFromLocationId] = useState<string | null>(fromLocation?.id ?? null);
  const [toLocationId, setToLocationId] = useState<string | null>(toLocation?.id ?? null);
  const [manualKm, setManualKm] = useState<string>('');
  const [manualHours, setManualHours] = useState<string>('');
  const [includeInbound, setIncludeInbound] = useState(true);
  const [includeOutbound, setIncludeOutbound] = useState(true);

  // Resetten wenn Dialog neu geöffnet wird
  useEffect(() => {
    if (open) {
      setFromLocationId(fromLocation?.id ?? null);
      setToLocationId(toLocation?.id ?? null);
      setManualKm('');
      setManualHours('');
      setIncludeInbound(true);
      setIncludeOutbound(true);
    }
  }, [open, fromLocation, toLocation]);

  const fromLoc = allLocations.find((l) => l.id === fromLocationId) ?? null;
  const toLoc = allLocations.find((l) => l.id === toLocationId) ?? null;

  // Haversine wenn beide Standorte GPS-Koordinaten haben
  const autoKm: number | null =
    fromLoc?.gpsDecimalLat != null &&
    fromLoc?.gpsDecimalLng != null &&
    toLoc?.gpsDecimalLat != null &&
    toLoc?.gpsDecimalLng != null
      ? Math.round(
          haversineKm(
            fromLoc.gpsDecimalLat,
            fromLoc.gpsDecimalLng,
            toLoc.gpsDecimalLat,
            toLoc.gpsDecimalLng
          ) * 10
        ) / 10
      : null;

  const effectiveKm = manualKm !== '' ? parseFloat(manualKm) || 0 : autoKm ?? 0;
  const autoHours = estimateTravelHours(effectiveKm);
  const effectiveHours = manualHours !== '' ? parseFloat(manualHours) || 0 : autoHours;

  const handleResetKm = () => setManualKm('');
  const handleResetHours = () => setManualHours('');

  const handleConfirm = () => {
    if (!includeInbound && !includeOutbound) {
      onClose();
      return;
    }

    const items: Partial<CalculationLineItem>[] = [];
    const now = new Date().toISOString();

    const fromName = fromLoc?.name ?? 'Start';
    const toName = toLoc?.name ?? asset.name;

    const base = {
      type: 'service' as const,
      isAutoGenerated: true,
      relatedAssetId: asset.id,
      materialId: null,
      serviceId: null,
      positionNumber: null,
      assetHeaderId: null,
      createdAt: now,
      updatedAt: now,
    };

    if (includeInbound) {
      items.push({
        ...base,
        id: uuid(),
        travelRole: 'inbound' as const,
        description: `Hinfahrt (km): ${fromName} → ${toName}`,
        quantity: effectiveKm,
        unit: 'km',
        unitPrice: 1.00,
        totalPrice: effectiveKm * 1.00,
      });
      items.push({
        ...base,
        id: uuid(),
        travelRole: 'inbound' as const,
        description: `Hinfahrt (Zeit): ${fromName} → ${toName}`,
        quantity: effectiveHours,
        unit: 'Std',
        unitPrice: 50.00,
        totalPrice: effectiveHours * 50.00,
      });
    }

    if (includeOutbound) {
      items.push({
        ...base,
        id: uuid(),
        travelRole: 'outbound' as const,
        description: `Rückfahrt (km): ${toName} → ${fromName}`,
        quantity: effectiveKm,
        unit: 'km',
        unitPrice: 1.00,
        totalPrice: effectiveKm * 1.00,
      });
      items.push({
        ...base,
        id: uuid(),
        travelRole: 'outbound' as const,
        description: `Rückfahrt (Zeit): ${toName} → ${fromName}`,
        quantity: effectiveHours,
        unit: 'Std',
        unitPrice: 50.00,
        totalPrice: effectiveHours * 50.00,
      });
    }

    onConfirm(items);
  };

  const handleClose = useCallback(() => onClose(), [onClose]);
  const handleBackdrop = useModalClose(open, handleClose);

  if (!open) return null;

  const isKmManual = manualKm !== '';
  const isHoursManual = manualHours !== '';

  return (
    <div
      className="fixed inset-0 bg-black/40 flex items-center justify-center z-50"
      onClick={handleBackdrop}
    >
      <div className="bg-white rounded-lg shadow-xl w-full max-w-lg mx-4 flex flex-col">
        {/* Header */}
        <div className="flex items-center justify-between px-6 py-4 border-b border-gray-200">
          <div className="flex items-center gap-2">
            <Car size={18} className="text-green-600" />
            <h2 className="text-lg font-bold">Fahrtblock konfigurieren</h2>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600 transition-colors">
            <X size={20} />
          </button>
        </div>

        {/* Body */}
        <div className="px-6 py-5 space-y-5">
          <p className="text-sm text-gray-600">
            Fahrtzeilen für <span className="font-semibold">{asset.name}</span> konfigurieren.
          </p>

          {/* Von / Nach */}
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Von (Startort)</label>
              <SearchableSelect
                value={fromLocationId}
                onChange={setFromLocationId}
                options={allLocations.map((l) => ({ id: l.id, label: l.name }))}
                placeholder="-- kein Standort --"
              />
            </div>
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Nach (Zielort)</label>
              <SearchableSelect
                value={toLocationId}
                onChange={setToLocationId}
                options={allLocations.map((l) => ({ id: l.id, label: l.name }))}
                placeholder="-- kein Standort --"
              />
            </div>
          </div>

          {/* Entfernung + Fahrzeit */}
          <div className="grid grid-cols-2 gap-4">
            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Entfernung (km)</label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  step="0.1"
                  min="0"
                  value={isKmManual ? manualKm : (autoKm ?? '').toString()}
                  onChange={(e) => setManualKm(e.target.value)}
                  placeholder={autoKm != null ? `Auto: ${autoKm}` : 'Manuell eingeben'}
                  className={`w-full px-3 py-2 border rounded-lg text-sm font-mono outline-none focus:ring-2 focus:ring-blue-500 ${
                    isKmManual ? 'border-orange-400 bg-orange-50' : 'border-gray-300'
                  }`}
                />
                {isKmManual && (
                  <button
                    type="button"
                    onClick={handleResetKm}
                    title="Auf Auto zurücksetzen"
                    className="p-1.5 text-gray-400 hover:text-orange-600 transition-colors shrink-0"
                  >
                    <RotateCcw size={14} />
                  </button>
                )}
              </div>
              {autoKm != null && !isKmManual && (
                <span className="text-xs text-gray-400">Haversine (Luftlinie)</span>
              )}
              {autoKm == null && !isKmManual && (
                <span className="text-xs text-gray-400">Kein GPS vorhanden</span>
              )}
            </div>

            <div className="flex flex-col gap-1.5">
              <label className="text-sm font-medium text-gray-700">Fahrzeit (h)</label>
              <div className="flex items-center gap-2">
                <input
                  type="number"
                  step="0.25"
                  min="0"
                  value={isHoursManual ? manualHours : autoHours.toString()}
                  onChange={(e) => setManualHours(e.target.value)}
                  placeholder={`Auto: ${autoHours}`}
                  className={`w-full px-3 py-2 border rounded-lg text-sm font-mono outline-none focus:ring-2 focus:ring-blue-500 ${
                    isHoursManual ? 'border-orange-400 bg-orange-50' : 'border-gray-300'
                  }`}
                />
                {isHoursManual && (
                  <button
                    type="button"
                    onClick={handleResetHours}
                    title="Auf Auto zurücksetzen"
                    className="p-1.5 text-gray-400 hover:text-orange-600 transition-colors shrink-0"
                  >
                    <RotateCcw size={14} />
                  </button>
                )}
              </div>
              {!isHoursManual && (
                <span className="text-xs text-gray-400">Berechnet: {effectiveKm} km ÷ 70 km/h</span>
              )}
            </div>
          </div>

          {/* Hinfahrt / Rückfahrt Checkboxen */}
          <div className="flex gap-6">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={includeInbound}
                onChange={(e) => setIncludeInbound(e.target.checked)}
                className="w-4 h-4 rounded accent-green-600"
              />
              <span className="text-sm font-medium text-gray-700">Hinfahrt</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={includeOutbound}
                onChange={(e) => setIncludeOutbound(e.target.checked)}
                className="w-4 h-4 rounded accent-green-600"
              />
              <span className="text-sm font-medium text-gray-700">Rückfahrt</span>
            </label>
          </div>

          {/* Info-Preview */}
          {(includeInbound || includeOutbound) && (
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-3 space-y-1">
              <p className="text-xs font-semibold text-gray-500 uppercase tracking-wide mb-1">
                Erzeugte Zeilen
              </p>
              {includeInbound && (
                <>
                  <div className="flex items-center gap-2 text-sm text-gray-700">
                    <Car size={13} className="text-green-500" />
                    <span>Hinfahrt (km): {fromLoc?.name ?? 'Start'} → {toLoc?.name ?? asset.name}</span>
                    <span className="text-xs text-gray-400 ml-auto">{effectiveKm} km · {(effectiveKm * 1.00).toFixed(2)} €</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-gray-700">
                    <Car size={13} className="text-green-500" />
                    <span>Hinfahrt (Zeit): {fromLoc?.name ?? 'Start'} → {toLoc?.name ?? asset.name}</span>
                    <span className="text-xs text-gray-400 ml-auto">{effectiveHours} Std · {(effectiveHours * 50.00).toFixed(2)} €</span>
                  </div>
                </>
              )}
              {includeOutbound && (
                <>
                  <div className="flex items-center gap-2 text-sm text-gray-700">
                    <Car size={13} className="text-blue-400" />
                    <span>Rückfahrt (km): {toLoc?.name ?? asset.name} → {fromLoc?.name ?? 'Start'}</span>
                    <span className="text-xs text-gray-400 ml-auto">{effectiveKm} km · {(effectiveKm * 1.00).toFixed(2)} €</span>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-gray-700">
                    <Car size={13} className="text-blue-400" />
                    <span>Rückfahrt (Zeit): {toLoc?.name ?? asset.name} → {fromLoc?.name ?? 'Start'}</span>
                    <span className="text-xs text-gray-400 ml-auto">{effectiveHours} Std · {(effectiveHours * 50.00).toFixed(2)} €</span>
                  </div>
                </>
              )}
            </div>
          )}
        </div>

        {/* Footer */}
        <div className="px-6 py-4 border-t border-gray-200 bg-gray-50 flex items-center justify-between">
          <button
            onClick={onClose}
            className="px-4 py-2 text-sm text-gray-700 bg-white border border-gray-300 rounded-lg hover:bg-gray-50 transition-colors"
          >
            Abbrechen
          </button>
          <button
            onClick={handleConfirm}
            className="px-5 py-2 text-sm font-medium bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
          >
            {includeInbound && includeOutbound
              ? 'Hin- & Rückfahrt hinzufügen'
              : includeInbound
              ? 'Hinfahrt hinzufügen'
              : includeOutbound
              ? 'Rückfahrt hinzufügen'
              : 'Überspringen'}
          </button>
        </div>
      </div>
    </div>
  );
}
